In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import collections

from sklearn.utils import shuffle
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

from tensorflow.keras.utils import to_categorical
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras import Sequential

from sklearn.preprocessing import Normalizer

%matplotlib inline

In [3]:
df = pd.read_csv("faces.csv")
df = df.drop(["Unnamed: 0"], axis = 1)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,target
0,0.624656,-0.447745,0.624376,0.168215,-1.183529,1.161336,1.180575,-1.458736,0.925821,0.236734,...,-1.062742,0.596569,0.682379,0.292868,0.409854,1.634237,0.249691,-0.189478,-1.783221,glauciane
1,0.921183,-0.228285,1.023043,-0.362588,-0.759581,0.905878,1.626263,-1.420151,1.193603,0.791741,...,-1.375485,0.683259,0.827911,-0.167854,0.260004,1.484647,0.228390,-0.471342,-1.681182,glauciane
2,-0.037906,-0.927606,0.960223,0.052220,-1.199638,0.768999,1.396971,-0.688852,0.781067,0.692422,...,-1.764692,0.959367,0.720395,-0.322032,0.306745,1.598800,-0.141811,-0.795695,-1.841082,glauciane
3,0.677615,-0.018155,0.723042,-0.119465,-1.317164,1.009346,1.103884,-1.569089,0.324309,0.405659,...,-0.621289,0.506900,0.757364,0.247419,0.131484,1.497606,0.284347,-0.406723,-2.066759,glauciane
4,0.841432,-0.305600,0.955496,-0.508191,-0.417205,1.673414,0.809553,-1.041964,1.069607,0.473020,...,-0.451649,0.114553,0.892378,0.363496,0.414226,2.106771,-0.339435,-0.562916,-2.133557,glauciane

In [4]:
df_novo = pd.read_csv("novo_morador.csv")
df_novo = df_novo.drop(["Unnamed: 0"], axis = 1)
df_novo.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,target
0,1.283068,-0.618400,0.416243,0.510427,-0.221535,0.561029,-0.253937,-1.000654,0.303981,0.263256,...,-0.642270,-0.212376,-1.240768,1.738863,-1.071481,-0.797167,0.174121,-0.127048,-1.585754,vitor
1,1.159242,-0.774388,0.539970,0.238755,-0.282508,0.251746,-0.195144,-0.951405,0.118425,0.535735,...,-0.554730,-0.103887,-1.628182,1.625349,-1.235085,-0.857136,0.058490,-0.164755,-1.411725,vitor
2,0.893742,-1.278235,0.147629,0.336178,-0.179283,0.727244,0.067278,-0.440429,-0.416185,0.702447,...,-0.713639,0.314201,-1.609076,1.267812,-0.694187,-0.396400,0.725545,0.003018,-0.705759,vitor
3,1.027963,-1.126672,0.455650,0.228816,-0.198916,0.446317,-0.096373,-0.753371,-0.355668,0.596956,...,-0.600778,0.384748,-1.748358,1.286287,-0.983976,-0.170629,0.502958,-0.106029,-0.773046,vitor
4,1.192816,-1.080215,0.441170,0.296942,-0.047265,0.681012,-0.050540,-0.643061,-0.417575,0.829963,...,-0.552952,0.013748,-1.776787,1.303885,-0.558961,-0.562623,0.446798,-0.101800,-0.807115,vitor

In [5]:
df = pd.concat([df,df_novo])
df.head()

,0,1,2,3,4,5,6,7,8,9,...,119,120,121,122,123,124,125,126,127,target
0,0.624656,-0.447745,0.624376,0.168215,-1.183529,1.161336,1.180575,-1.458736,0.925821,0.236734,...,-1.062742,0.596569,0.682379,0.292868,0.409854,1.634237,0.249691,-0.189478,-1.783221,glauciane
1,0.921183,-0.228285,1.023043,-0.362588,-0.759581,0.905878,1.626263,-1.420151,1.193603,0.791741,...,-1.375485,0.683259,0.827911,-0.167854,0.260004,1.484647,0.228390,-0.471342,-1.681182,glauciane
2,-0.037906,-0.927606,0.960223,0.052220,-1.199638,0.768999,1.396971,-0.688852,0.781067,0.692422,...,-1.764692,0.959367,0.720395,-0.322032,0.306745,1.598800,-0.141811,-0.795695,-1.841082,glauciane
3,0.677615,-0.018155,0.723042,-0.119465,-1.317164,1.009346,1.103884,-1.569089,0.324309,0.405659,...,-0.621289,0.506900,0.757364,0.247419,0.131484,1.497606,0.284347,-0.406723,-2.066759,glauciane
4,0.841432,-0.305600,0.955496,-0.508191,-0.417205,1.673414,0.809553,-1.041964,1.069607,0.473020,...,-0.451649,0.114553,0.892378,0.363496,0.414226,2.106771,-0.339435,-0.562916,-2.133557,glauciane

In [6]:
X = np.array(df.drop(["target"], axis=1))
X.shape

(29557, 128)

In [7]:
y = np.array(df.target)
y.shape
print(y[0])

glauciane

In [8]:
trainX, trainY = shuffle(X, y, random_state = 0) # misturando tudo

108
218
251
284
488
491
616
653
680
731
786
844
865
884
941
1029
1107
1112
1193
1262
1263
1302
1342
1490
1576
1645
1666
1683
1699
1726
1754
1766
1783
1804
1811
1888
1955
2055
2084
2142
2360
2433
2480
2484
2521
2633
2724
2735
2816
2828
2913
3072
3080
3105
3165
3215
3271
3274
3285
3325
3359
3420
3434
3488
3510
3532
3593
3662
3666
3680
3719
3722
3829
3872
3958
3995
4114
4194
4243
4245
4274
4348
4352
4552
4581
4598
4727
4948
5079
5146
5169
5191
5208
5234
5332
5548
5556
5703
5736
5740
5745
5836
5949
5982
6033
6103
6111
6158
6173
6258
6449
6476
6488
6502
6628
6629
6630
6947
7002
7008
7079
7125
7130
7136
7243
7264
7337
7347
7376
7421
7437
7505
7515
7520
7590
7624
7661
7783
7803
7884
7904
7915
7970
7991
7997
8054
8107
8176
8214
8247
8326
8367
8378
8424
8447
8509
8532
8623
8630
8654
8675
8690
8749
8756
8811
9046
9319
9350
9404
9408
9417
9493
9510
9558
9608
9631
9692
9728
9753
9830
9833
9893
9932
10048
10068
10083
10109
10154
10278
10284
10287
10339
10355
10356
10392
10401
10413
10456
10532
10554
10562
10587
10606
10795
10826
10877
10882
10906
10952
11141
11223
11287
11427
11544
11661
11671
11695
11898
11956
12011
12019
12025
12064
12152
12198
12201
12229
12266
12275
12348
12458
12472
12568
12608
12635
12721
12725
12818
12821
12837
12845
12853
12873
12978
13095
13180
13255
13259
13414
13570
13573
13803
13936
14158
14260
14330
14358
14400
14557
14610
14612
14861
15027
15031
15057
15097
15163
15197
15243
15349
15427
15503
15522
15547
15676
15755
15848
15874
16038
16096
16112
16120
16166
16178
16196
16253
16268
16357
16359
16390
16424
16437
16556
16626
16730
16824
16853
16916
16992
17024
17117
17151
17207
17218
17257
17311
17346
17347
17363
17381
17385
17401
17411
17543
17551
17586
17673
17819
17908
18002
18093
18106
18153
18161
18216
18230
18242
18249
18251
18318
18321
18356
18365
18412
18502
18535
18568
18669
18779
18816
18848
18918
19018
19149
19195
19276
19290
19342
19622
19761
19768
19852
19873
19883
20011
20027
20033
20169
20222
20242
20348
20382
20556
20633
20705
20782
20807
20810
20848
20897
20906
20940
20944
21078
21148
21219
21232
21526
21755
21769
21824
21961
21975
21976
22006
22045
22068
22170
22393
22417
22440
22578
22585
22674
22742
22753
22790
22966
23093
23102
23117
23217
23221
23243
23270
23311
23318
23401
23503
23545
23555
23561
23608
23696
23703
23711
23800
23830
23857
23895
23906
23944
23947
24018
24027
24106
24218
24292
24313
24316
24347
24372
24413
24421
24428
24569
24609
24619
24659
24683
24690
24836
24863
24945
24977
25040
25149
25233
25399
25462
25527
25559
25601
25613
25619
25724
25736
25779
25911
25940
25957
26011
26040
26050
26053
26069
26097
26131
26204
26265
26309
26471
26477
26488
26518
26540
26578
26641
26651
26719
26749
26815
26823
26909
26933
26950
27099
27104
27185
27209
27212
27252
27339
27413
27444
27473
27649
27749
27794
27844
27853
27885
27898
27923
27940
27953
28237
28273
28298
28468
28540
28573
28624
28671
28812
28904
28908
28913
29010
29183
29194
29231
29321
29388

## TRATANDO AS LABELS

In [9]:
out_encoder = LabelEncoder() # enumerando as saidas
out_encoder.fit(trainY)

LabelEncoder()

In [10]:
trainY = out_encoder.transform(trainY)
n_classes = len(np.unique(trainY))
n_classes

5

### KERAS

In [11]:
trainY = to_categorical(trainY)
trainY

array([[0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.]], dtype=float32)

In [12]:
model = models.Sequential()
model.add(layers.Dense(64, activation = 'relu', input_shape = (128,)))
model.add(layers.Dropout(0.5))
model.add(layers.Dense(n_classes, activation = 'softmax'))
 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                8256

 dropout (Dropout)           (None, 64)                0

 dense_1 (Dense)             (None, 5)                 325

=================================================================
Total params: 8,581
Trainable params: 8,581
Non-trainable params: 0
_________________________________________________________________

In [13]:
model.compile(optimizer="adam", loss= "categorical_crossentropy", metrics=['accuracy'])

In [14]:
model.fit(trainX, trainY, epochs=20, batch_size = 8)

Epoch 1/20
3695/3695 [==============================] - 2s 580us/step - loss: 0.0573 - accuracy: 0.9832
Epoch 2/20
3695/3695 [==============================] - 2s 574us/step - loss: 0.0022 - accuracy: 0.9996
Epoch 3/20
3695/3695 [==============================] - 2s 575us/step - loss: 0.0016 - accuracy: 0.9996
Epoch 4/20
3695/3695 [==============================] - 2s 576us/step - loss: 9.5400e-04 - accuracy: 0.9997
Epoch 5/20
3695/3695 [==============================] - 2s 581us/step - loss: 7.5201e-04 - accuracy: 0.9997
Epoch 6/20
3695/3695 [==============================] - 2s 581us/step - loss: 5.6486e-04 - accuracy: 0.9997
Epoch 7/20
3695/3695 [==============================] - 2s 599us/step - loss: 2.3404e-04 - accuracy: 0.9999
Epoch 8/20
3695/3695 [==============================] - 2s 587us/step - loss: 7.5509e-04 - accuracy: 0.9998
Epoch 9/20
3695/3695 [==============================] - 2s 587us/step - loss: 5.7619e-04 - accuracy: 0.9998
Epoch 10/20
3695/3695 [==============================] - 2s 586us/step - loss: 4.6672e-04 - accuracy: 0.9998
Epoch 11/20
3695/3695 [==============================] - 2s 584us/step - loss: 2.0746e-04 - accuracy: 1.0000
Epoch 12/20
3695/3695 [==============================] - 2s 579us/step - loss: 2.1237e-04 - accuracy: 0.9999
Epoch 13/20
3695/3695 [==============================] - 2s 582us/step - loss: 3.5815e-04 - accuracy: 0.9999
Epoch 14/20
3695/3695 [==============================] - 2s 587us/step - loss: 4.4188e-04 - accuracy: 0.9997
Epoch 15/20
3695/3695 [==============================] - 2s 582us/step - loss: 2.1728e-04 - accuracy: 0.9999
Epoch 16/20
3695/3695 [==============================] - 2s 581us/step - loss: 3.9364e-04 - accuracy: 0.9999
Epoch 17/20
3695/3695 [==============================] - 2s 580us/step - loss: 6.8429e-04 - accuracy: 0.9999
Epoch 18/20
3695/3695 [==============================] - 2s 578us/step - loss: 2.1742e-04 - accuracy: 0.9999
Epoch 19/20
3695/3695 [==============================] - 2s 579us/step - loss: 1.8910e-04 - accuracy: 0.9999
Epoch 20/20
3695/3695 [==============================] - 2s 584us/step - loss: 4.6549e-05 - accuracy: 1.0000

In [19]:
df.to_csv('faces.csv')
model.save("faces.h5")